version: "3.3"

services:
  db:
    container_name: mysql-consumer
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: challenge-root
      MYSQL_DATABASE: challenge-php

  nginx:
    container_name: nginx-consumer
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8084:80"
    depends_on:
      - db
  
  php:
    container_name: php-consumer
    build: images/php
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9001:9000"
    depends_on:
      - db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: challenge-root